package Matthew.view;

import Matthew.model.vo.ResultadosVO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author bruno
 */
public class Resultado extends javax.swing.JFrame {

    String[] sContas;
    double[] dRes;

    /**
     * Creates new form Resultado
     */
    public Resultado() {
        initComponents();
    }

    public Resultado(List<ResultadosVO> l) {
        initComponents();
        init(l);
    }

    public Resultado(String[] sContas, double[] dRes) {
        initComponents();
        this.sContas = sContas;
        this.dRes = dRes;
        //init();

    }

    public void init(List<ResultadosVO> l) {
        DefaultTableModel model = (DefaultTableModel) tblResultado.getModel();
        l.forEach((lst1) -> {
            model.addRow(new Object[]{lst1.getsNome(), lst1.getdValor()});
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Conta", "Resultado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResultado);

        getContentPane().add(jScrollPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables
}
